spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: root
    password: 1qaz3edc
    url: jdbc:mysql://172.96.193.200/injury
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: injury
flyway:
  baseline-on-migrate: true
  encoding: UTF-8
server:
  port: 8080